### ISSUE TITLE
Fix parallel invocation

### ISSUE THREAD

**Issue by annashamray** [maykinmedia/zgw-consumers#13]
* Fix this line:
https://github.com/maykinmedia/zgw-consumers/blob/6ec6af61f11d4884be363eeef865df50bf2fe2e1/zgw_consumers/service.py#L64

* Check all other `parallel` invocation in the code

**Comment by sergei-maertens** [comment]
Was fixed ind5dc0c9aa6d77af71e9aaf0110387957962222e9
