### ISSUE TITLE
Function should have Optional in return value

### ISSUE THREAD

**Issue by shea-maykinmedia** [maykinmedia/zgw-consumers#24]
Minor issue but I noticed that `get_service` in `models/Service` has a return type of `'Service'` but may also return `None`.  https://github.com/maykinmedia/zgw-consumers/blob/master/zgw_consumers/models.py#L127

I believe this should be `Optional["Service"]`.

**Comment by sergei-maertens** [comment]
Correct, feel free to make a PR for this!
