### ISSUE TITLE
Check the request conforms to the OAS spec before sending.

### ISSUE THREAD

**Issue by CharString** [maykinmedia/zgw-consumers#59]
Currently it's possible to place requests that are out of spec of the service, i.e. no checks are done whether parameters adhere to the schemas defined in the OAS.

Being conservative with what we send would help in multiple ways:
 - by not sending request that are out of spec, a consumer becomes less of a vector to poke at the service
 - a service may work with out of spec requests now, but might fix their implementation and start giving failure responses. Catching these misuses of the client early could help tracing down problems with implementations of consumer applications. And prevent hard to debug/reproduce bugs down the line.

**Comment by sergei-maertens** [comment]
-> should probably be an optional strict-mode, as there's a difference between untrusted user-configuration and trusted programmatic calls where you'd want to skip that overhead.

**Comment by sergei-maertens** [comment]
Note that we're in the process of removing the OAS integration because it's unreliable across different vendors.

I'd suggest that if these kind of checks/validation are required, to handle them in your own wrapper.
