### ISSUE TITLE
RuntimeError: Model class simple_certmanager.models.Certificate doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

### ISSUE THREAD

**Issue by SilviaAmAm** [maykinmedia/zgw-consumers#67]
Adding zgw-consumers as a dependency without adding `simple_certmanager` to `INSTALLED_APPS` causes error when running migrations.

I think it can be added to the README?

**Comment by sergei-maertens** [comment]
Yep, and to docs/quickstart.rst too!
