### ISSUE TITLE
`get_paginated_results` does not work with `ape_pie.APIClient`

### ISSUE THREAD

**Issue by stevenbal** [maykinmedia/zgw-consumers#81]
The `get_paginated_results` function does not work with the recommended `ape_pie.APIClient`, because it relies on the `client.list` operation and passes `request_kwargs`: https://github.com/maykinmedia/zgw-consumers/blob/main/zgw_consumers/service.py#L25

**Comment by sergei-maertens** [comment]
As discussed in Slack - feel free to add the pagination helper from OF in this package: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/contrib/zgw/clients/utils.py#L23
