### ISSUE TITLE
Configurable timeout for `Service`

### ISSUE THREAD

**Issue by stevenbal** [maykinmedia/zgw-consumers#84]
@sergei-maertens with OIP we were running into timeout issues regarding the Open Forms client: https://github.com/open-formulieren/open-forms-client-django/pull/6, which does not directly concern zgw-consumers, but do you think it would be useful to add the option to configure timeouts for `zgw_consumers.Service`?

**Comment by sergei-maertens** [comment]
I'd say it's still extremely situational because one endpoint is not like the other.

The OF endpoint is too  slow and needs to be fixed. I'd opt for a fix in the OF client here to specify a timeout and use that explicitly until the API itself is updated.
